// <auto-generated />
using System;
using ASP_Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_Server.Migrations
{
    [DbContext(typeof(TimetabledbContext))]
    [Migration("20220208184028_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ASP_Server.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Classroom_number")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Frame")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("ASP_Server.Models.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Discipline_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("ASP_Server.Models.Faculty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Faculty_name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");
                });

            modelBuilder.Entity("ASP_Server.Models.Lesson_time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Lesson_finish")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int>("Lesson_number")
                        .HasColumnType("int");

                    b.Property<string>("Lesson_start")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Lesson_times");
                });

            modelBuilder.Entity("ASP_Server.Models.Lesson_type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Lesson_types");
                });

            modelBuilder.Entity("ASP_Server.Models.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("ASP_Server.Models.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Abbreviated_speciality")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Speciality_name")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.HasKey("Id");

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("ASP_Server.Models.Study_group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Course")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Education_form")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("FacultyId")
                        .HasColumnType("int");

                    b.Property<string>("Group_name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("SpecialityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("Study_groups");
                });

            modelBuilder.Entity("ASP_Server.Models.Timetable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClassroomId")
                        .HasColumnType("int");

                    b.Property<int?>("DisciplineId")
                        .HasColumnType("int");

                    b.Property<int?>("Lesson_timeId")
                        .HasColumnType("int");

                    b.Property<int?>("Lesson_typeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int?>("Study_groupId")
                        .HasColumnType("int");

                    b.Property<int?>("Week_dayId")
                        .HasColumnType("int");

                    b.Property<int?>("Week_parityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("Lesson_timeId");

                    b.HasIndex("Lesson_typeId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("Study_groupId");

                    b.HasIndex("Week_dayId");

                    b.HasIndex("Week_parityId");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("ASP_Server.Models.Week_day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Week_days");
                });

            modelBuilder.Entity("ASP_Server.Models.Week_parity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Parity")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Week_parities");
                });

            modelBuilder.Entity("ASP_Server.Models.Study_group", b =>
                {
                    b.HasOne("ASP_Server.Models.Faculty", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.HasOne("ASP_Server.Models.Speciality", "Speciality")
                        .WithMany()
                        .HasForeignKey("SpecialityId");

                    b.Navigation("Faculty");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("ASP_Server.Models.Timetable", b =>
                {
                    b.HasOne("ASP_Server.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId");

                    b.HasOne("ASP_Server.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId");

                    b.HasOne("ASP_Server.Models.Lesson_time", "Lesson_time")
                        .WithMany()
                        .HasForeignKey("Lesson_timeId");

                    b.HasOne("ASP_Server.Models.Lesson_type", "Lesson_type")
                        .WithMany()
                        .HasForeignKey("Lesson_typeId");

                    b.HasOne("ASP_Server.Models.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId");

                    b.HasOne("ASP_Server.Models.Study_group", "Study_group")
                        .WithMany()
                        .HasForeignKey("Study_groupId");

                    b.HasOne("ASP_Server.Models.Week_day", "Week_day")
                        .WithMany()
                        .HasForeignKey("Week_dayId");

                    b.HasOne("ASP_Server.Models.Week_parity", "Week_parity")
                        .WithMany()
                        .HasForeignKey("Week_parityId");

                    b.Navigation("Classroom");

                    b.Navigation("Discipline");

                    b.Navigation("Lesson_time");

                    b.Navigation("Lesson_type");

                    b.Navigation("Professor");

                    b.Navigation("Study_group");

                    b.Navigation("Week_day");

                    b.Navigation("Week_parity");
                });
#pragma warning restore 612, 618
        }
    }
}
